kind: Service
apiVersion: v1
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
spec:
  type: NodePort
  selector:
    app: ${project.artifactId}
  ports:
  - port: 8080
    targetPort: 8080
    name: http